### PR TITLE
chore: rem rewards weight from stake table

### PR DESCRIPTION
**Pull request by ericHgorski**

### CODE REVIEW

**Review by restorenode — COMMENTED** [review]
@JoshuaBrigati can we get the CSS updated on the staking tables after removing the `Rewards weight` column?

image

**Comment by terencelimzhengwei** [comment]
@ericHgorski - we'll need to remove reward weights from these two places too
Screenshot 2023-07-12 at 5 00 56 PM
Screenshot 2023-07-12 at 5 01 09 PM

**Comment by ericHgorski** [comment]
> @ericHgorski - we'll need to remove reward weights from these two places too Screenshot 2023-07-12 at 5 00 56 PM Screenshot 2023-07-12 at 5 01 09 PM

missed those! should be fixed now though @terencelimzhengwei. What styling change would you advocate for @terran6 ?

**Comment by restorenode** [comment]
> > @ericHgorski - we'll need to remove reward weights from these two places too Screenshot 2023-07-12 at 5 00 56 PM Screenshot 2023-07-12 at 5 01 09 PM
> 
> missed those! should be fixed now though @terencelimzhengwei. What styling change would you advocate for @terran6 ?

I think we just need to move the second column over to the left to create more space.  Although, maybe we should defer to design on what they think would be best.

**Comment by JoshuaBrigati** [comment]
@terran6 I added some space between the right 2 columns.
Screenshot 2023-07-13 at 10 18 44 AM

**Review by restorenode — APPROVED** [review]

**Pull request merged**
