### PR TITLE
Improve functionality of pagination when viewing proposals in Voting status by only paginating when showing all proposals

### PR DESCRIPTION
**Pull request by esoderquist**
Previously, pagination was negatively impacting whitelist functionality leading to fewer than PAGINATION_LENGTH whitelisted proposals being displayed on each page.

### CODE REVIEW

**Comment by esoderquist** [comment]
Related to paging behavior - in researching this PR, I believe I have uncovered an issue with the LCD endpoint https://columbus-lcd.terra.dev/cosmos/gov/v1beta1/proposals. Specifically, requesting a reverse ordered set of paginated records works great for the first set, but when fetching the second set using the next page key, a record is skipped between returned sets. This only seems to occur if pagination.count_total=true is included on the initial call. I'll continue to research and will submit github issue/PR to the appropriate repo once I have an opportunity to review further.

Repro:

- Note the order of the first 9 proposals returned by https://columbus-lcd.terra.dev/cosmos/gov/v1beta1/proposals?proposal_status=2&pagination.limit=9&pagination.count_total=true&pagination.reverse=true
- Fetch the first 3 records: https://columbus-lcd.terra.dev/cosmos/gov/v1beta1/proposals?proposal_status=2&pagination.limit=9&pagination.count_total=true&pagination.reverse=true
- Fetch the next 3 records: https://columbus-lcd.terra.dev/cosmos/gov/v1beta1/proposals?proposal_status=2&pagination.limit=9&pagination.count_total=true&pagination.reverse=true&pagination.key=NEXTKEYFROMPREVCALL

Note that the second call above properly returns the most recent 3 records, along with the record total, but the subsequent paged call skips the 4th most recent record.

**Comment by vegasmorph** [comment]
@simcheolhwan this is the big that I was talking about.

**Comment by esoderquist** [comment]
This PR has been updated via commit 1ac34b4, which works around the underlying "skipped item" issue currently presenting in the cosmos api when paginating through datasets with odd numbers of records.

This commit introduces one additional api call to fetch the total number of records each time the proposal view context changes (e.g. switching between voting, deposit, passed, rejected). Calls to the api to retrieve the actual proposals are done without the count_total flag to avoid the skipped item issue.

Effectively, this PR now does two things:

* Improves the display of whitelisted proposals on the voting tab by eliminating paging for whitelisted items. Paging is maintained when show all is selected
* Works around the api-side behavior observed when pagination.reverse and pagination.count_total is true where subsequent pages are missing the first record (e.g. the page offset of indexed + 1 ahead of where it should be). I have opened issue #133 to separate documentation of that behavior from this PR

**Comment by esoderquist** [comment]
Abandoning this PR in favor of in-progress work toward infinite-scroll pagination for governance proposals.

**Pull request closed without merging**
