### PR TITLE
NFT image fallback to image_data

### PR DESCRIPTION
**Pull request by wrjanan**

### CODE REVIEW

**Comment by wrjanan** [comment]
@simcheolhwan 

Hi Cheol Hwan,

Added a reference to image_data if `getIpfsGateway(image)` returns empty.

**Comment by wrjanan** [comment]
Removed the image_data fallback.

Instead added `data:` allowance for getIpfsGatway function in accordance to data uris
https://www.rfc-editor.org/rfc/rfc2397#section-2

**Comment by simcheolhwan** [comment]
Any practical examples for this? @wrjanan

**Comment by wrjanan** [comment]
On Terra Classic, if we select Lunapunks as an NFT collection (terra1qfy2nfr0zh70jyr3h4ns9rzqx4fl8rxpf09ytv).
We will be able to view the NFTs in the station.

If you have a wallet address, I can send you one to test this commit.
@simcheolhwan

**Comment by wrjanan** [comment]
Yes, specifically for images, we can wrap the raw image data with the few following sub types:
- data:image/svg
- data:image/svg+xml
- data:image/jpg 
- data:image/jpeg 
- data:image/png

Main practical example of this is to allow for on chain storage and changing of information. Example if we have a NFT which handles our passport information, updating our profile picture directly through the smart contract can be a possible practical example where we might want to store image_data in the blockchain.

**Pull request merged**
