### PR TITLE
St 809 do not allow user to enter amounts larger than the amount being held web extension

### PR DESCRIPTION
**Pull request by mwmerz**
- [x] include tax in max calculation

### CODE REVIEW

**Comment by mwmerz** [comment]
* With max sufficiently calculated, normal form validation will block submission of transactions out of range.

**Review by restorenode — CHANGES_REQUESTED** [review]
I think we should not allow the user to input any number larger than the maximum.  I think the same should be done on extension.

https://github.com/terra-money/station/assets/30275692/85911dc8-99bf-41da-a68f-f897725950be

**Comment by mwmerz** [comment]
The form validation will not allow it to submit. This has been the ux and convention since the beginning. I do not agree that this is something that requires change.

**Comment by mwmerz** [comment]
At best, we can restrict the rendering of the fee box. But I do not agree that this is a valuable use of our limited time.  The goal here is to prevent loss of funds due to failed txs if the user clicks max.

**Comment by restorenode** [comment]
@mwmerz would we not at least want to disable the `Send` button until all requirements are met?

Also, it seems the fee is not being properly subtracted when attempting a SWTH transaction:

https://github.com/terra-money/station/assets/30275692/3c0f5417-1ff7-4e18-b98b-a788d5d9aa06

**Comment by mwmerz** [comment]
Disabling send was my gut reaction too.  However, the form validation still prevents submission. 

Regarding posting fees and taxes, yes, I agree that those should be listed, for both carbon and classic.

We can hack a way in for now. The right way to do this will be to add tax and fee strategies based on chain, which would require a refactor of that component. 

Otherwise we're using a switch to manually solve for 2 edge cases and are not future-proofing the component against other exotic fee structures in the future.

**Review by restorenode — APPROVED** [review]
Other than the above, looks good.

**Pull request merged**
