### PR TITLE
feat: validate amount inputs

### PR DESCRIPTION
**Pull request by ericHgorski**
amount inputs should only accept number characters and `.`

### CODE REVIEW

**Review by restorenode — DISMISSED** [review]
Let's try not to allow the user to input many leading zeros (00001 resolves to 1). Also, it would be good to force a leading 0 for any user-inputted decimal values.

https://github.com/terra-money/station/assets/30275692/f53d0469-5d1e-4078-9091-0f1a9e411052

**Comment by terencelimzhengwei** [comment]
There is a weird up/down selector thing now which we should remove
Screenshot 2023-07-12 at 5 03 51 PM

**Comment by ericHgorski** [comment]
> There is a weird up/down selector thing now which we should remove Screenshot 2023-07-12 at 5 03 51 PM

Should be fixed now @terencelimzhengwei! Ill apply the same to extension.

**Review by restorenode — CHANGES_REQUESTED** [review]
Error when trying to send a float value.

https://github.com/terra-money/station/assets/30275692/ba495882-cdc9-4f8f-b10d-9c9ec93fbe64

**Comment by ericHgorski** [comment]
> Error when trying to send a float value.
> 
>  Screen.Recording.2023-07-13.at.12.12.58.AM.mov

good catch, should be solved now.

**Review by restorenode — APPROVED** [review]

**Pull request merged**
