### PR TITLE
Use new IBC channels

### PR DESCRIPTION
**Pull request by alecande11**
This PR use the new IBC channels from this PR: https://github.com/terra-money/station-assets/pull/161
It allows direct chain-to-chain IBC transfers without having to pass through Terra

### CODE REVIEW

**Review by ericHgorski — COMMENTED** [review]
The error Im experiencing: 
Screenshot 2023-07-05 at 12 11 58 PM
Screenshot 2023-07-05 at 12 12 03 PM

**Review by restorenode — CHANGES_REQUESTED** [review]
Failure upon LUNA IBC transaction.

https://github.com/terra-money/station/assets/30275692/e4f53bb8-bc6e-4616-95c0-319b0f9de319

**Review by restorenode — CHANGES_REQUESTED** [review]
Terra listed under chains and unsupported chains.

image

**Comment by alecande11** [comment]
> 559ae2a

@terran6 This is the expected behaviour.
The axlUSDC that you see on Terra under the chain section are those sent directly from Axelar to Terra.
Those in the Unsupported Chains section are sent through a different path and therefore not usable in most Terra applications.

**Review by restorenode — APPROVED** [review]
IBC transfers worked as expected.  IBC failures indicate a bad channel specified on either of the assets repos or nodes failing to relay transactions on chains along the transaction path.

**Pull request merged**
