### PR TITLE
fix: chain menu dupes

### PR DESCRIPTION
**Pull request by ericHgorski**

### CODE REVIEW

**Comment by restorenode** [comment]
What problem is this fixing?

**Comment by ericHgorski** [comment]
> What problem is this fixing?

https://terra-money.atlassian.net/browse/ST-776

**Review by restorenode — APPROVED** [review]
I don't see the duplicates on production, but the code is all good.

**Comment by ericHgorski** [comment]
> I don't see the duplicates on production, but the code is all good.

You should be able to see it on the extension. Only happens on web occasionally.

**Pull request merged**
