### PR TITLE
feat: disable gov on certain chains

### PR DESCRIPTION
**Pull request by ericHgorski**
To be tested in conjunction with: https://github.com/terra-money/station-assets/pull/208

### CODE REVIEW

**Review by restorenode — COMMENTED** [review]
Which chains in particular should have gov disabled?

**Comment by ericHgorski** [comment]
> To be tested in conjunction with: [terra-money/station-assets#208](https://github.com/terra-money/station-assets/pull/208)

You can see those chains here @terran6

**Review by restorenode — COMMENTED** [review]
Should the disabled chains even show up on the options here?  I would guess `Neutron` shouldn't be available for selection on Governance?

Screenshot 2023-09-15 at 4 33 26 PM

**Review by restorenode — CHANGES_REQUESTED** [review]
Still getting `Neutron` showing up.  Running the related `station-assets` branch locally and updating the variables on both Web and Extension to reflect that.

image

**Comment by ericHgorski** [comment]
> Still getting `Neutron` showing up. Running the related `station-assets` branch locally and updating the variables on both Web and Extension to reflect that.
> 
> image

Does the `chains.json` being returned by localhost include both disabledModules for Neutron, i.e. `"disabledModules":["staking","gov"]`? Also ensure you have the latest changes on that branch as naming was switched from `governance` to `gov`.

**Comment by restorenode** [comment]
> > Still getting `Neutron` showing up. Running the related `station-assets` branch locally and updating the variables on both Web and Extension to reflect that.
> > image
> 
> Does the `chains.json` being returned by localhost include both disabledModules for Neutron, i.e. `"disabledModules":["staking","gov"]`? Also ensure you have the latest changes on that branch as naming was switched from `governance` to `gov`.

Looks like the `gov` disabled module is not available on Neutron when run locally.

image

**Review by restorenode — APPROVED** [review]

**Pull request merged**
