### PR TITLE
ST-426: show all history

### PR DESCRIPTION
**Pull request by alecande11**

### CODE REVIEW

**Comment by terran6** [comment]
@alecande11 seems that the `All` option is overriding any single chain selection when moving away from the active page.

**Review by restorenode — CHANGES_REQUESTED** [review]
It seems that the All option is overriding any single chain selection when moving away from the active page.

**Comment by alecande11** [comment]
@terran6 ChainFilter is fixed now

**Review by restorenode — APPROVED** [review]
🌟

**Pull request merged**
