### PR TITLE
Change Terra's finder to Extraterrestrial

### PR DESCRIPTION
**Pull request by moonmidas**
As seen by this community poll:
https://twitter.com/TheMoonMidas/status/1474052382539587591?s=20

95% of the community requests protocols and dapps on Terra to use Extraterrestrial finder due to its full set of features.

Appreciate it!

### CODE REVIEW

**Comment by AgilePatryk** [comment]
Fully supportuje of that. Every time I inspect a transaction and it opens (by default) in Terra Finder, I feel sudden urge to copy the tx # and paste it into Extraterrestrial Finder.
Please make my life easier!

**Comment by 0xjimm** [comment]
Full support. ET makes exploring the Terra blockchain a breeze.

**Comment by IncioMan** [comment]
Full support from me! I much prefer extraterrestrial tbh!

**Comment by simcheolhwan** [comment]
We don't change the official Finder like this right now.
However, we admire the usefulness of ET Finder, understand users' requests, and above all, plan a new collaboration with the ET Finder team now.

**Comment by Chinoman10** [comment]
> We don't change the official Finder like this right now. However, we admire the usefulness of ET Finder, understand users' requests, and above all, plan a new collaboration with the ET Finder team now.

May we ask for the reason behind your decision?

**Comment by etienne-napoleone** [comment]
Writing here too for bette visibility:
How about adding a "explorer URL" field to station extension "new network"?

It's the same way as currently work metamask.
It's always better to offer choice.

While I love ET, making ET the default explorer has a few consequences:
- probable a LOT more traffic being sent down there, need to be sure it will handle it (probably will but still)
- while I have 100% trust in Kazzy, I still think it is good that the default explorer is under control of TFL from a security standpoint
- TFL might not maintain or care about finder as much. But finder is the main driver behind fcd (which could be called "finder API" at this point) development, which most projects use also as they don't have their own indexers.

Only downside I can see is that it forces the same URL paths as TFL's finder on new explorers. Not too bad imo

**Comment by sascha1337** [comment]
The idea with the on-page Explorer toggle is also fancy imho

**Comment by Chinoman10** [comment]
ET Finder already has the exact same paths, so that isn't really a problem.
But yes, I agree that offering choice is the best course to go 💪

**Comment by simcheolhwan** [comment]
Update:
We are still dealing with this issue with ET team.
I was quiet until everything has been decided, but this issue is still going on.

**Comment by simcheolhwan** [comment]
92245b5 closes this

**Pull request closed without merging**
